name: php_codesniffer;

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Run phpcs
        run: composer exec --verbose phpcs -- --standard=PSR12 src public
